### ISSUE TITLE
xgb: modifiers "stick" if the key is released outside wde's window

### ISSUE THREAD

**Issue by rowanworth** [skelterjohn/go.wde#34]
Can reproduce with the wdetest program (probably requires sloppy-focus):

1) give focus to a wde window
2) press (and hold) the left_super key
3) move the mouse out of the wde window and give focus to a different window
4) release the super key

Subsequent keypresses in the originally-focused wde window report "super" as part of the chord.

**Comment by sqweek** [comment]
Fixed by #40
