### ISSUE TITLE
With go 1.12 using _Ctype_int is an error

### ISSUE THREAD

**Issue by raff** [skelterjohn/go.wde#56]
Trying to compile on Macos with go 1.12 fails with these errors:

       # github.com/skelterjohn/go.wde/cocoa
       cocoa/cocoa_darwin.go:90:25: identifier "_Ctype_int" may conflict with identifiers generated by cgo
       cocoa/cocoa_darwin.go:90:44: identifier "_Ctype_int" may conflict with identifiers generated by cgo
       cocoa/cocoa_darwin.go:96:14: identifier "_Ctype_int" may conflict with identifiers generated by cgo

The fix consists in replace _Ctype_int with C.int

**Comment by skelterjohn** [comment]
Up for contributing that change? :)

**Comment by raff** [comment]
Submitted pull-request
